export const CITIES = [
  "Toshkent",
  "Samarqand",
  "Buxoro",
  "Andijon",
  "Farg'ona",
  "Namangan",
  "Nukus",
  "Qarshi",
  "Termiz",
  "Jizzax",
  "Guliston",
  "Navoiy",
  "Urganch",
  "Xiva",
  "Kokand",
  "Margilon",
  "Chirchiq",
  "Angren",
] as const;

export const CATEGORIES: { name: string; slug: string; icon: string }[] = [
  { name: "Santexnik", slug: "santexnik", icon: "🔧" },
  { name: "Elektrik", slug: "elektrik", icon: "💡" },
  { name: "Repetitor", slug: "repetitor", icon: "📚" },
  { name: "Go'zallik ustasi", slug: "gozallik-ustasi", icon: "💅" },
  { name: "Tozalash xizmati", slug: "tozalash-xizmati", icon: "🧹" },
  { name: "Fotograf", slug: "fotograf", icon: "📷" },
  { name: "Kompyuter ustasi", slug: "kompyuter-ustasi", icon: "💻" },
  { name: "Duradgor", slug: "duradgor", icon: "🪚" },
  { name: "Bo'yoqchi", slug: "boyoqchi", icon: "🎨" },
  { name: "Muzlatgich ustasi", slug: "muzlatgich-ustasi", icon: "🧊" },
  { name: "Ko'chirish xizmati", slug: "kochirish-xizmati", icon: "🚚" },
  { name: "SMM mutaxassisi", slug: "smm-mutaxassisi", icon: "📱" },
  { name: "Video montajchi", slug: "video-montajchi", icon: "🎬" },
  { name: "Dizayner", slug: "dizayner", icon: "🖌️" },
  { name: "Haydovchi", slug: "haydovchi", icon: "🚗" },
  { name: "Bog'bon", slug: "bogbon", icon: "🌱" },
];
